### ISSUE TITLE
Propose data models

### ISSUE THREAD

**Issue by salekd** [AstroPlant/astroplant-backend#2]
Propose data models/schemas for Kafka and PostgreSQL.
- Sensor data should be stored in some kind of a generic schema format. Each data point should keep a reference the kit ID and the configuration used.
- Configurations should define what to measure and how often. It should also be easy to find when was a certain configuration active/disabled.
- Users/kits/projects and passwords.

**Comment by tomcur** [comment]
Initial model has been added in 1268ed88fb09b1dfcc4f22093ca58832382d6af9.

Some more thought should be given to representation of kit configurations.

**Comment by salekd** [comment]
We will need a separate model/table for the realtime messages.

**Comment by tomcur** [comment]
> We will need a separate model/table for the realtime messages.

Done in 21730f2114ff78ad43b96d281338d2ce7251b42d.

**Comment by tomcur** [comment]
In the data model kits can have some additional information attached to them, such as latitude and longitude. Should this information instead be attached to kit configurations, such that each measurement's coordinates can be tracked, even when the kit is moved? From an ease of use perspective both for users and front-end developers, it's best to have the information be attached to kits.

Perhaps we should require users to create a new kit object when they move their kit to a new location. In that case, we might want to add some "archival" functionality, where a kit can be marked as archived, to allow front-ends to distinguish active kits from archived ones.

**Comment by thiemehennis** [comment]
the question is: what info should be tied to a kit? I think that
longitude/latitude is not always that relevant. Basically we work in
experimental setups and projects. If a new growth cycle is started on a
different place by the same user, what then? If we continue with a growth
cycle in another room in the same building, what then? If the kit is moving
as part of an exhibition? I guess ultimately every kit needs an owner who
takes care of the kit and coordinates all activities. The archival
functionality - imo - should then apply to ownership. Every owner has a
track record of experiments and data collection etc. What do you think?


--
Thieme Hennis PhD // +31651855220 // Amsterdam, Den Haag

**Comment by tomcur** [comment]
In essence, it seems we have a few things impacting the measurements that we might or might not want to keep track of. A few things: 

* the configuration of the peripherals and recipes;
* the specific object being monitored (usually the plant being grown);
* the specific kit model ("AstroPlant version X", or some other model);
* some other things related to the kit (coordinates, whether it's near a window, etc.).

Maybe we can have kits, kit configurations, and also some "kit situation description."

Configurations and situation descriptions would be independent of each other. Measurements would be linked against both a kit configuration and (optionally?) a situation description.

**Comment by tomcur** [comment]
Doing it this ^ way also allows ignoring the situation descriptions for now as they could be added later without much effort. We do need location coordinates if we want to display a world map with kit positions, though.

**Comment by thiemehennis** [comment]
hey Thomas, I'm not sure how important 'AstroPlant version X' is going to be. I guess there are going to be a couple of standard configurations (for specific experiments), but it's the configuration that essentially determines the setup. A configuration then should also include the dimensions and other properties of a kit. What do you think?

The other things seem logical to keep track of.

**Comment by tomcur** [comment]
Data models (ORM) are at https://github.com/AstroPlant/astroplant-backend/blob/ae8162dda6359f73073d9203074d65113653c7cb/database/astroplant_database/specification.py.

The MQTT message format is defined e.g. here: https://github.com/AstroPlant/astroplant-kit/blob/08fa6737e4007bb242d325f1cfcfc5e075335bca/astroplant_kit/proto/astroplant.capnp.
