### ISSUE TITLE
Write a client to upload images to Minio

### ISSUE THREAD

**Issue by salekd** [AstroPlant/astroplant-backend#31]
A client running on the kit needs to be able to send images from the camera to the object store. The images should go into a bucket with the following folder structure `kit_id/date/image`. At the same time, a link to the image should be sent over MQTT to the database, using a dedicated data model.

**Comment by tomcur** [comment]
Maybe the image should be sent over MQTT.

Then, the mqtt-api places it in the object store and sends a message over Kafka for the kafka-db-connector to update the database.

This way the kit is kept lightweight.

**Comment by tomcur** [comment]
Images/blobs are now sent over MQTT. The blobs shouldn't become too large (a few MBs at most, MQTT isn't really meant for larger uploads). This way kits communicate with the backend exclusively over MQTT. If absolutely necessary we can revisit this and add streaming uploads in the future.
