### ISSUE TITLE
Use Mosquitto authentication plugin

### ISSUE THREAD

**Issue by salekd** [AstroPlant/astroplant-backend#36]

**Comment by tomcur** [comment]
Refer to https://github.com/AstroPlant/astroplant-api/blob/6a106239efd284c14877b30b2e39a47a41aa1e3d/astroplant-auth/src/hash.rs#L146-L168

Here, we have password `It all adds up to normality.` ran through pbkdf2 with the following parameters:

| Parameter | Value |
| ------------- | ------- |
| Hashing function | sha256 |
| Salt (as bytes taken from UTF8 encoding of the string) | `Z416JHE8vSmaiamV5TRz` |
| Iterations | 2000 |

The resulting hash as base64-encoded bytes is `z3y6FvWAZtyQe6TV+O/oyhC3oqnF8KJdlB5Lphi+Lwg=`.

This is all encoded as a string in the following way, which the Mosquitto authentication plugin should be able to understand:

```
pbkdf2$sha256$2000$Z416JHE8vSmaiamV5TRz$z3y6FvWAZtyQe6TV+O/oyhC3oqnF8KJdlB5Lphi+Lwg=
```

**Comment by salekd** [comment]
Mosquitto with the auth plugin is in place. At the moment, I am using the following tables in PostgreSQL:

```
CREATE TABLE account(
   id SERIAL PRIMARY KEY,
   username VARCHAR(255) UNIQUE NOT NULL,
   pw VARCHAR(255) NOT NULL,
   super INTEGER
);
```

```
 id | username |                                 pw                                  | super
----+----------+---------------------------------------------------------------------+-------
  1 | admin    | PBKDF2$sha256$901$7kBBUBI7ReFDQFuq$+VEZa51aIJdDqeusuXM/CxeIw+4QEY4/ |     1
  2 | public   | PBKDF2$sha256$901$5G4N4uzBveLtQtXr$bUQ5Z0hkojiGycqe7y/8ILK2peMH+NKD |     0
```

```
CREATE TABLE acls(
   id SERIAL PRIMARY KEY,
   username VARCHAR(255) UNIQUE NOT NULL,
   topic VARCHAR(255) NOT NULL,
   rw INTEGER
);
```

```
 id | username |  topic   | rw
----+----------+----------+----
  1 | public   | public/# |  7
```

We need to embed the above to the existing data model. We can use the existing `users` table for the passwords.

```
 id | username | password | email_address | use_gravatar | gravatar_alternative
```

However, I think we need the extra table for ACLs. Let us assume `user1` is linked to `kit2`. Then we need a row in the `acls` table like this:

```
 id | username |  topic   | rw
----+----------+----------+----
  2 | user1   | kit/kit2/measurement/+ |  7
```

@Beskhue do you agree? Populating such `acls` table should be part of the cluster management API functionality. It should also be part of `connector.py` when running with `insert-develop-data` (which defines the `k_develop` kit for testing and we should also have a test user for that).

**Comment by tomcur** [comment]
Mosquitto with the authentication plugin is declared here: https://github.com/AstroPlant/astroplant-k8s/tree/f7ef2cc254f6b38fe79dbfcca8d3cafbc9139650/deployment/mqtt

Hashing in `astroplant-api` is implemented here: https://github.com/AstroPlant/astroplant-api/blob/375b3144156e507b5558a108996caff17475f4db/astroplant-auth/src/hash.rs#L89-L96

We might want to add a hashing implementation in `./database` in this repository in the future, with utilities to add kits or change kit passwords.
