### ISSUE TITLE
Support both aggregate and real-time messages

### ISSUE THREAD

**Issue by salekd** [AstroPlant/astroplant-backend#8]
The `kit/+/measurement/aggregate` topic is hardcoded in `mqtt-api/astroplant_mqtt_api.py` at the moment. Make sure the code supports a realtime topic as well.

**Comment by tomcur** [comment]
If the main AstroPlant API will rebroadcast real-time measurements over websockets for consumption by front-end clients, then `mqtt-api` need not consume real-time measurements: instead, the main API will consume from MQTT directly and rebroadcast.

**Comment by salekd** [comment]
It depends whether we want to store the realtime messages in the database as well. I think it is a good practice to keep raw data. The commit is there, let us discuss whether to keep it or not.
https://github.com/AstroPlant/astroplant-backend/commit/072573c217e791df4b1c05031d2effd801aba0c3

Otherwise, I agree we can handle the realtime traffic elsewhere to forward to the frontend clients. Why websockets and not MQTT?

**Comment by salekd** [comment]
The realtime messages should be written to the database in batches. This can be easily done by polling data from Kafka in longer time intervals.

The code will be deployed on Kubernetes in two separate pods, one for realtime and one for aggregate messages.

**Comment by tomcur** [comment]
Implemented in 21730f2114ff78ad43b96d281338d2ce7251b42d.

Note for clarity "real-time measurements" are renamed "raw measurements."
